name: Deploy to prod Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY  }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/my-app:${{ github.run_id }} .
        
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/my-app:latest .
          
      - name: Configure docker
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/my-app:${{ github.run_id }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/my-app:latest
    

      - name: Deploy app to Cloud Run
        run: |
          gcloud run deploy okha \
            --image ${{ secrets.ARTIFACT_REGISTRY }}/my-app:${{ github.run_id }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --project ${{ secrets.PROJECT_ID }} \
            --min-instances=1 \
            --max-instances=1 \
            --port=80 \
            --no-cpu-boost \
            --cpu-throttling \
            --ingress internal-and-cloud-load-balancing
